from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 560)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setEnabled(True)
        self.label_name.setGeometry(QtCore.QRect(110, 30, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        self.label_name.setFont(font)
        self.label_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_name.setObjectName("label_name")
        self.input_name = QtWidgets.QLineEdit(self.centralwidget)
        self.input_name.setGeometry(QtCore.QRect(180, 30, 200, 22))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        self.input_name.setFont(font)
        self.input_name.setText("")
        self.input_name.setObjectName("input_name")
        self.label_email = QtWidgets.QLabel(self.centralwidget)
        self.label_email.setEnabled(True)
        self.label_email.setGeometry(QtCore.QRect(110, 65, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        self.label_email.setFont(font)
        self.label_email.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_email.setObjectName("label_email")
        self.input_email = QtWidgets.QLineEdit(self.centralwidget)
        self.input_email.setGeometry(QtCore.QRect(180, 65, 200, 22))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        self.input_email.setFont(font)
        self.input_email.setObjectName("input_email")
        self.label_age = QtWidgets.QLabel(self.centralwidget)
        self.label_age.setEnabled(True)
        self.label_age.setGeometry(QtCore.QRect(110, 100, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        self.label_age.setFont(font)
        self.label_age.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_age.setObjectName("label_age")
        self.input_age = QtWidgets.QLineEdit(self.centralwidget)
        self.input_age.setGeometry(QtCore.QRect(180, 100, 200, 22))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        self.input_age.setFont(font)
        self.input_age.setObjectName("input_age")
        self.label_phone = QtWidgets.QLabel(self.centralwidget)
        self.label_phone.setEnabled(True)
        self.label_phone.setGeometry(QtCore.QRect(43, 135, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        self.label_phone.setFont(font)
        self.label_phone.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_phone.setObjectName("label_phone")
        self.input_phone = QtWidgets.QLineEdit(self.centralwidget)
        self.input_phone.setGeometry(QtCore.QRect(180, 135, 200, 22))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        self.input_phone.setFont(font)
        self.input_phone.setMaxLength(17)
        self.input_phone.setObjectName("input_phone")
        self.label_address = QtWidgets.QLabel(self.centralwidget)
        self.label_address.setEnabled(True)
        self.label_address.setGeometry(QtCore.QRect(93, 170, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        self.label_address.setFont(font)
        self.label_address.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_address.setObjectName("label_address")
        self.label_gender = QtWidgets.QLabel(self.centralwidget)
        self.label_gender.setEnabled(True)
        self.label_gender.setGeometry(QtCore.QRect(110, 340, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        self.label_gender.setFont(font)
        self.label_gender.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_gender.setObjectName("label_gender")
        self.combo_gender = QtWidgets.QComboBox(self.centralwidget)
        self.combo_gender.setGeometry(QtCore.QRect(180, 340, 97, 22))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        self.combo_gender.setFont(font)
        self.combo_gender.setObjectName("combo_gender")
        self.combo_gender.addItem("")
        self.combo_gender.setItemText(0, "")
        self.combo_gender.addItem("")
        self.combo_gender.addItem("")
        self.label_education = QtWidgets.QLabel(self.centralwidget)
        self.label_education.setEnabled(True)
        self.label_education.setGeometry(QtCore.QRect(83, 375, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        self.label_education.setFont(font)
        self.label_education.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_education.setObjectName("label_education")
        self.combo_education = QtWidgets.QComboBox(self.centralwidget)
        self.combo_education.setGeometry(QtCore.QRect(180, 375, 200, 22))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        self.combo_education.setFont(font)
        self.combo_education.setObjectName("combo_education")
        self.combo_education.addItem("")
        self.combo_education.setItemText(0, "")
        self.combo_education.addItem("")
        self.combo_education.addItem("")
        self.combo_education.addItem("")
        self.combo_education.addItem("")
        self.combo_education.addItem("")
        self.combo_education.addItem("")
        self.combo_education.addItem("")
        self.input_address = QtWidgets.QTextEdit(self.centralwidget)
        self.input_address.setGeometry(QtCore.QRect(180, 170, 301, 151))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        self.input_address.setFont(font)
        self.input_address.setObjectName("input_address")
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(180, 430, 90, 28))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        self.btn_save.setFont(font)
        self.btn_save.setObjectName("btn_save")
        self.btn_clear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear.setGeometry(QtCore.QRect(350, 430, 90, 28))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        self.btn_clear.setFont(font)
        self.btn_clear.setObjectName("btn_clear")
        self.label_footer = QtWidgets.QLabel(self.centralwidget)
        self.label_footer.setEnabled(True)
        self.label_footer.setGeometry(QtCore.QRect(130, 490, 281, 20))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(9)
        self.label_footer.setFont(font)
        self.label_footer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_footer.setObjectName("label_footer")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Form Validation"))
        self.label_name.setText(_translate("MainWindow", "Name:"))
        self.label_email.setText(_translate("MainWindow", "Email:"))
        self.label_age.setText(_translate("MainWindow", "Age:"))
        self.label_phone.setText(_translate("MainWindow", "Phone Number:"))
        self.input_phone.setInputMask(_translate("MainWindow", "+62 000 0000 0000"))
        self.input_phone.setText(_translate("MainWindow", "+62   "))
        self.label_address.setText(_translate("MainWindow", "Address:"))
        self.label_gender.setText(_translate("MainWindow", "Gender:"))
        self.combo_gender.setItemText(1, _translate("MainWindow", "Male"))
        self.combo_gender.setItemText(2, _translate("MainWindow", "Female"))
        self.label_education.setText(_translate("MainWindow", "Education:"))
        self.combo_education.setItemText(1, _translate("MainWindow", "Elementary School"))
        self.combo_education.setItemText(2, _translate("MainWindow", "Junior High School"))
        self.combo_education.setItemText(3, _translate("MainWindow", "Senior High School"))
        self.combo_education.setItemText(4, _translate("MainWindow", "Diploma"))
        self.combo_education.setItemText(5, _translate("MainWindow", "Bachelor\'s Degree"))
        self.combo_education.setItemText(6, _translate("MainWindow", "Master\'s Degree"))
        self.combo_education.setItemText(7, _translate("MainWindow", "Doctoral Degree"))
        self.btn_save.setText(_translate("MainWindow", "Save"))
        self.btn_clear.setText(_translate("MainWindow", "Clear"))
        self.label_footer.setText(_translate("MainWindow", "Regia Puspa Amaranthi - F1D022156"))
